# **Lab 2**

## Handling Data in Python

> **Credit note:** Part of this lab was adapted from the adaptation by [Volodymyr Kuleshov](http://web.stanford.edu/~kuleshov/) and [Isaac Caswell](https://symsys.stanford.edu/viewing/symsysaffiliate/21335) for Stanford University's `CS228`, which was originally from Stanford University's `CS231n` Python tutorial by Justin Johnson (http://cs231n.github.io/python-numpy-tutorial/).

## Introduction

Last week, we looked at some fundamentals for Python programming, including **list**, **tuples** and **dictionaries** -- three essential data types that form useful structures that data can be represented by. We did not cover arrays (NB: lists are _not_ arrays), for arrays in Python is are handled by a fast library called **Numpy**. We will later look at tabular data (basically, data in the form of tables) and play with **Pandas**, another library which existed for the purpose of handling and manipulating tabular data efficiently.

## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with Numpy. If you are familiar with C++/Java, working with these arrays can be a big sigh of relief :-)

To use Numpy, we first need to import the `numpy` package:

In [ ]:
import numpy as np

What we are doing here with **as** is to give an "alias" to the numpy class that we are importing for use. From now on, we can just use _np_ to call functions instead of its full name _numpy_.

You may check for its version...

In [ ]:
np.__version__       # double underscore on both sides

'1.23.5'

In [ ]:
#!pip install --upgrade numpy

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print (type(a), a.shape, a[0], a[1], a[2])        # observe what is printed out
a[0] = 5                 # Change an element of the array
print(a)                # ..oh this is easier..

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.shape)         # 2 row 3 columns
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Numpy also provides many functions to create specific format of arrays:

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros. Note the floating point .
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix. eye literally means 'I'
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.34111372 0.22951359]
 [0.41591879 0.31860478]]


### Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
print()
b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[2 3]
 [6 7]]


Important note: A slice of an array is a "view" into the same data, so modifying it will modify the original array.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])
print(a)

2
77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower _rank_,
while using only slices yields an array of the same _rank_ as the
original array (Note that "rank" here is slightly different from the matrix rank you learn in linear algebra. Read: https://www.pythoninformer.com/python-libraries/numpy/anatomy-of-array/):

In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print (row_r1, row_r1.shape)
print (row_r2, row_r2.shape)
print (row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print ()
print (col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


#### **Integer array indexing**
When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print (a[[0, 1, 2], [0, 1, 0]])       # ... fancy!
print (a.shape)
print()

# The above example of integer array indexing is equivalent to this:
print (np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
(3, 2)

[1 4 5]


In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print (a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print (np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print (a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print (a[np.arange(4), b])       # prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print (a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


#### **Boolean array indexing**
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print (bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print (a[bool_idx])

# We can do all of the above in a single concise statement:
print (a[a > 2])

[3 4 5 6]
[3 4 5 6]


There are many other useful functions in Numpy such as `mean`, `min`, `max` which can help us find useful information from data. Explore here: https://docs.scipy.org/doc/numpy/reference/routines.statistics.html

## Basic File Access

You can also explicitly read from and write to files directly in your code. Python makes working with files pretty simple. Let's try firstly with a text file by obtaining a *file object* using open. Then, proceed to read the contents of the file.

> Because you are on **Colab**, you need to upload files into the Colab session in order to use it here. The interface is easy to use: Click on the folder icon at the left side (third icon vertically), then click on the upload icon (first icon horizontally), then choose the file "hello.txt". If you are using **Jupyter Notebook**, you just need to ensure the file is in the same directory as the notebook file.

In [ ]:
#To open a text file, use:
fh = open("hello.txt", "r")

#To read a text file, use:
fh = open("hello.txt","r")
print(fh.read())
print()
fh.close()

#To read one line at a time, use:
fh = open("hello.txt", "r")
print(fh.readline())
fh.close()

#To read a list of lines use:
fh = open("hello.txt", "r")
print(fh.readlines())
fh.close()

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 

['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \n', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. \n', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. \n', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui off

We can also attempt to write some content to the file:

In [ ]:
#To write to a file, use:
fh = open("hello2.txt","w")
fh.write("Hello World")
fh.close()

#To write to a file, use:
fh = open("hello2.txt", "w")
lines_of_text = ["a line of text", "another line of text", "a third line"]
lot = [line + '\n' for line in lines_of_text]       # this is necessary to ensure we go to next line. It is not auto!
fh.writelines(lot)
fh.close()

#To append to file, use:
fh = open("hello2.txt", "a")
fh.write("Hello World again")
fh.close

fh = open("hello2.txt", "r")
print(fh.read())

a line of text
another line of text
a third line
Hello World again


> If you don't see the file in the side Files pane, you may need to right-click on it and select Refresh to refresh the directory list. Then, you should see the "hello2.txt" file listed.

Another commonly used data file is a comma-separated value, or **CSV** file. CSV files contain lines (or rows) that are comma separated (literally separated by commas) into individual pieces of data.

![](http://www.manifold.net/doc/mfd9/images/eg_formats_csv01_01.png)

Of course, the position of data should be consistent across the lines -- the data before the first comma (for all lines) should carry the same information, and so is the data before the second comma, and so on.

You can also open CSV files in spreadsheet editors such as MS Excel, and view them in the form of columns.

In [ ]:
import csv

The following code opens a CSV file and reads the whole bunch of the data. (**Note**: Remember to upload the file to Colab session if you are using Colab!)

Then a loop goes through each list in the csv_reader object and prints it. Observe the output. Compare with the same data when opened in a spreadsheet editor.

In [ ]:
with open('clinic1M.csv') as csv_file:
    csv_reader = list(csv.reader(csv_file, delimiter=','))
    # ...puts each line of data from csv into a list
    for row in csv_reader:
        print(row)

['id', 'name', '', 'address', 'address2', 'state_id', 'postcode', 'city', 'tel', 'fax', 'website', 'email', 'image', 'latitude', 'longitude', 'likes', 'rating', 'status']
['1', 'Klinik 1 Malaysia Alma Jaya', ' Alma Jaya', 'No. 38, Tingkat Bawah , Lorong Alma Jaya II, Taman Alma Jaya Bukit Mertajam', 'Seberang Perai Tengah, Pulau Pinang', '9', '14000', 'Bukit Mertajam', '454521033', '', '', '', '', '0', '0', '0', '0', 'NEW']
['2', 'Klinik 1 Malaysia Aulong', ' Aulong', 'N0 51 &53, Jalan Medan Bersatu, Taman Medan Bersatu,Taiping', 'Larut Matang, Perak', '7', '34000', 'Taiping', '05-8068867', '', '', '', '', '0', '0', '0', '0', 'NEW']
['3', 'Klinik 1 Malaysia Bandar Lela', ' Bandar Lela', 'Lot 7A &7B, Tingkat Bawah, Blok B Mile 1, Jalan Leila Sandakan', 'Sandakan, Sabah', '12', '90700', 'Bandar Lela', '08-6132046', '', '', '', '', '0', '0', '0', '0', 'NEW']
['4', 'Klinik 1 Malaysia Bandar Puteri Jaya', ' Bandar Puteri Jaya', 'No.41, Tingkat Bawah, Jalan Puteri Jaya 1/1, Bandar Puteri Jay

**Q1**: Write some code:
<ol type="a">
<li>to extract all the names of the clinics from the data into another new list. (You can use list comprehension!)</li>
<li>to count the total number of clinics</li>
</ol>

In [ ]:
with open('clinic1M.csv') as csv_file:
    csv_reader = list(csv.reader(csv_file, delimiter=','))
    # fill in your code
    clinic_names = [x[1] for x in csv_reader]
    clinic_names.pop(0)
    n = len(clinic_names)


print(clinic_names)
print("Total number of 1M clinics: ", len(clinic_names))




['Klinik 1 Malaysia Alma Jaya', 'Klinik 1 Malaysia Aulong', 'Klinik 1 Malaysia Bandar Lela', 'Klinik 1 Malaysia Bandar Puteri Jaya', 'Klinik 1 Malaysia Bandar seri Iskandar', 'Klinik 1 Malaysia Bandar Sri Alam', 'Klinik 1 Malaysia Bandar Sri Indah', 'Klinik 1 Malaysia Batu Berendam', 'Klinik 1 Malaysia Seremban Jaya', 'Klinik 1 Malaysia Seri Pengkalan', 'Klinik 1 Malaysia Sri Stulang', 'Klinik 1 Malaysia Batu Kawan', 'Klinik 1 Malaysia Batu Melintang', 'Klinik 1 Malaysia Bercham', 'Klinik 1 Malaysia Binjai', 'Klinik 1 Malaysia Bukit Beruntung', 'Klinik 1 Malaysia Bukit Katil', 'Klinik 1 Malaysia Bukit Payong', 'Klinik 1 Malaysia Bukit Sentosa', 'Klinik 1 Malaysia Bundusan Square', 'Klinik 1 Malaysia Cakerapurnama', 'Klinik 1 Malaysia Desa Rejang', 'Klinik 1 Malaysia Kg Padang Jaya', 'Klinik 1 Malaysia Kota Bharu', 'Klinik 1 Malaysia Bandar seri Iskandar', 'Klinik 1 Malaysia Intan Baiduri', 'Klinik 1 Malaysia Jalan Teku', 'Klinik 1 Malaysia Jelawat', 'Klinik 1 Malaysia Jelutong', 'Klini

Once you are done with the question above, let's try to write the extracted clinic names data to a new CSV file called "`clinic_list.csv`". The following code does just that. Check the contents of the CSV file to ensure the data is intact.

In [ ]:
with open('clinic_list.csv', mode='w', newline='') as clinic_list:
    clinic_writer = csv.writer(clinic_list, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    for n in clinic_names:
        clinic_writer.writerow([n])

"clinic_list.csv" should be created in your Colab session. To download it to your own commputer, right-click on the file and choose Download. Open the file in your computer and examine its contents.

For more information, look up the documentation: https://docs.python.org/3/library/csv.html

## Pandas

Pandas is a powerful library written for Python for data manipulation and analysis. Its name is derived from the term "panel data", an econometrics term for data sets that include observations over multiple time periods for the same individuals.

**Note**: Pandas need Numpy to be installed.

In [ ]:
import pandas as pd

_Series_ and _DataFrame_ are two important structures in Pandas that you will use frequently and interchangeably.

#### Series

A Series is a one-dimensional object similar to an array, list, or column in a table. It will assign a labeled index to each item in the Series. By default, each item will receive an index label from 0 to N, where N is the length of the Series minus one.

In [ ]:
s = pd.Series([7, 'Heisenberg', 3.14, -1789710578, 'Happy Eating!'])
print(s)

0                7
1       Heisenberg
2             3.14
3      -1789710578
4    Happy Eating!
dtype: object


The numbers that you see in the first "column" (actually it's not a column of the data), are actually the indices of the data rows. The other column is the actual data column.

Alternatively, you can specify an index of your choice when creating the Series, but it isn't very intuitive.

In [ ]:
s = pd.Series([7, 'Heisenberg', 3.14, -1789710578, 'Happy Eating!'], index=['A', 'Z', 'C', 'Y', 'E'])
print(s)

A                7
Z       Heisenberg
C             3.14
Y      -1789710578
E    Happy Eating!
dtype: object


You can use `iloc` and `loc` to access data. `iloc` takes an integer index, which may not be very intuitive. `loc` returns the data based on the index.

In [ ]:
s.iloc[4]

'Happy Eating!'

In [ ]:
s.loc['C']

3.14

The Series constructor can convert a dictonary as well, using the keys of the dictionary as its index. How convenient! Pandas actually uses this dictionary representation in its structure, as you will begin to notice slowly.

In [ ]:
d = {'Chicago': 1000, 'New York': 1300, 'Portland': 900, 'San Francisco': 1100, 'Austin': 450, 'Boston': None}
cities = pd.Series(d)
print(cities)

Chicago          1000.0
New York         1300.0
Portland          900.0
San Francisco    1100.0
Austin            450.0
Boston              NaN
dtype: float64


Note: Assigning value "None" will show up as "NaN" (or Not a Number). Think "Null" in other languages you are familiar with.

You can use the index (or a bunch of indices) to select specific items from the Series.

In [ ]:
cities[['Chicago', 'Portland', 'San Francisco']]

Chicago          1000.0
Portland          900.0
San Francisco    1100.0
dtype: float64

Think dictionaries...use a key to get the value

In [ ]:
cities['Chicago']

1000.0

cities < 1000 returns a Series of True/False values, which we then pass to our Series cities, returning the corresponding True items.

**Recall**: We came across this form of *boolean indexing* earlier when dealing with Numpy. Looks like this also works in Pandas.

In [ ]:
less_than_1000 = cities < 1000
print(less_than_1000)
print()
print(cities[less_than_1000])

Chicago          False
New York         False
Portland          True
San Francisco    False
Austin            True
Boston           False
dtype: bool

Portland    900.0
Austin      450.0
dtype: float64


In [ ]:
print('Seattle' in cities)
print('San Francisco' in cities)

False
True


All these are quick ways of filtering through the data to retrieve or search for something. If you want to find cities that are less than 1000, you may use boolean indexing. If you want to find if a specific city exists, you can also use a boolean condition with "in" operator.

Mathematical operations can be done using scalars and functions.

In [ ]:
# square city values
np.square(cities)

Chicago          1000000.0
New York         1690000.0
Portland          810000.0
San Francisco    1210000.0
Austin            202500.0
Boston                 NaN
dtype: float64

You can add two Series together, which returns a union of the two Series with the addition occurring on the shared index values. Values on either Series that did not have a shared index will produce a NULL/NaN (not a number).

In [ ]:
print(cities[['Chicago', 'New York', 'Portland']])
print()
print(cities[['Austin', 'New York']])
print()
print(cities[['Chicago', 'New York', 'Portland']] + cities[['Austin', 'New York']])

Chicago     1000.0
New York    1300.0
Portland     900.0
dtype: float64

Austin       450.0
New York    1300.0
dtype: float64

Austin         NaN
Chicago        NaN
New York    2600.0
Portland       NaN
dtype: float64


NULL checking can be performed with `isnull` and `notnull`.

In [ ]:
print(cities.isnull())
print()
print(cities[cities.isnull()])

Chicago          False
New York         False
Portland         False
San Francisco    False
Austin           False
Boston            True
dtype: bool

Boston   NaN
dtype: float64


#### DataFrame

A DataFrame is similar to Excel workbook $–$ you have column names referring to *columns* and you have *rows*, which can be accessed with use of row numbers. The essential difference being that column names and row numbers are known as column index and row index, in the case of dataframes.

Pandas actually makes things even more convenient. Reading a CSV is as simple as calling the `read_csv` function.

In [ ]:
df = pd.read_csv('clinic1M.csv')      # or you may use any CSV file
df

id                                      name               Unnamed: 2  \
0    1               Klinik 1 Malaysia Alma Jaya                Alma Jaya   
1    2                  Klinik 1 Malaysia Aulong                   Aulong   
2    3             Klinik 1 Malaysia Bandar Lela              Bandar Lela   
3    4      Klinik 1 Malaysia Bandar Puteri Jaya       Bandar Puteri Jaya   
4    5    Klinik 1 Malaysia Bandar seri Iskandar     Bandar seri Iskandar   
5    6         Klinik 1 Malaysia Bandar Sri Alam          Bandar Sri Alam   
6    7        Klinik 1 Malaysia Bandar Sri Indah         Bandar Sri Indah   
7    8           Klinik 1 Malaysia Batu Berendam            Batu Berendam   
8    9           Klinik 1 Malaysia Seremban Jaya            Seremban Jaya   
9   10          Klinik 1 Malaysia Seri Pengkalan           Seri Pengkalan   
10  11             Klinik 1 Malaysia Sri Stulang              Sri Stulang   
11  12              Klinik 1 Malaysia Batu Kawan               Batu Kawan   
12  13          Klinik 1 Malaysia Batu Melintang           Batu Melintang   
13  14                 Klinik 1 Malaysia Bercham                  Bercham   
14  15                  Klinik 1 Malaysia Binjai                   Binjai   
15  16         Klinik 1 Malaysia Bukit Beruntung          Bukit Beruntung   
16  17             Klinik 1 Malaysia Bukit Katil              Bukit Katil   
17  18            Klinik 1 Malaysia Bukit Payong             Bukit Payong   
18  19           Klinik 1 Malaysia Bukit Sentosa            Bukit Sentosa   
19  20         Klinik 1 Malaysia Bundusan Square          Bundusan Square   
20  21           Klinik 1 Malaysia Cakerapurnama            Cakerapurnama   
21  22             Klinik 1 Malaysia Desa Rejang              Desa Rejang   
22  23          Klinik 1 Malaysia Kg Padang Jaya           Kg Padang Jaya   
23  24              Klinik 1 Malaysia Kota Bharu               Kota Bharu   
24  25    Klinik 1 Malaysia Bandar seri Iskandar     Bandar seri Iskandar   
25  26           Klinik 1 Malaysia Intan Baiduri            Intan Baiduri   
26  27              Klinik 1 Malaysia Jalan Teku               Jalan Teku   
27  28                 Klinik 1 Malaysia Jelawat                  Jelawat   
28  29                Klinik 1 Malaysia Jelutong                 Jelutong   
29  30                  Klinik 1 Malaysia Kangar                   Kangar   
30  31          Klinik 1 Malaysia Kg Padang Jaya           Kg Padang Jaya   
31  32              Klinik 1 Malaysia Kota Bharu               Kota Bharu   
32  33             Klinik 1 Malaysia Kota Kenari              Kota Kenari   
33  34           Klinik 1 Malaysia Lembah Subang            Lembah Subang   
34  35             Klinik 1 Malaysia Matang Jaya              Matang Jaya   
35  36          Klinik 1 Malaysia Pengkalan Batu           Pengkalan Batu   
36  37                 Klinik 1 Malaysia Perkasa                  Perkasa   
37  38                   Klinik 1 Malaysia PJS 6                    PJS 6   
38  39           Klinik 1 Malaysia Seremban Jaya            Seremban Jaya   
39  40          Klinik 1 Malaysia Seri Pengkalan           Seri Pengkalan   
40  41             Klinik 1 Malaysia Sri Stulang              Sri Stulang   
41  42          Klinik 1 Malaysia Kg Padang Jaya           Kg Padang Jaya   
42  43         Klinik 1 Malaysia Sulaman Sentral          Sulaman Sentral   
43  44              Klinik 1 Malaysia Sungai Ara               Sungai Ara   
44  45             Klinik 1 Malaysia Sungai Plan              Sungai Plan   
45  46     Klinik 1 Malaysia Taman Gombak Permai      Taman Gombak Permai   
46  47  Klinik 1 Malaysia Taman Kempadang Makmur   Taman Kempadang Makmur   
47  48             Klinik 1 Malaysia Taman Manis              Taman Manis   
48  49         Klinik 1 Malaysia Taman Megah Ria          Taman Megah Ria   
49  50            Klinik 1 Malaysia Taman Melati             Taman Melati   
50  51        Klinik 1 Malaysia Taman Pagoh Jaya         Taman Pagoh Jaya   


We can use the head or tail method to print the first/last N rows of our data frame. We could accomplish the same thing using the method. The `iloc` method allows us to retrieve rows and columns by position. In order to do that, we’ll need to specify the positions of the rows that we want, and the positions of the columns that we want as well.

In [ ]:
print(df.head()) #prints first N rows. Default: 5

   id                                    name             Unnamed: 2  \
0   1             Klinik 1 Malaysia Alma Jaya              Alma Jaya   
1   2                Klinik 1 Malaysia Aulong                 Aulong   
2   3           Klinik 1 Malaysia Bandar Lela            Bandar Lela   
3   4    Klinik 1 Malaysia Bandar Puteri Jaya     Bandar Puteri Jaya   
4   5  Klinik 1 Malaysia Bandar seri Iskandar   Bandar seri Iskandar   

                                             address  \
0  No. 38, Tingkat Bawah , Lorong Alma Jaya II, T...   
1  N0 51 &53, Jalan Medan Bersatu, Taman Medan Be...   
2  Lot 7A &7B, Tingkat Bawah, Blok B Mile 1, Jala...   
3  No.41, Tingkat Bawah, Jalan Puteri Jaya 1/1, B...   
4  N0.32 Blod D, Bangunan Rumah Kedai, Bandar Ser...   

                              address2  state_id  postcode  \
0  Seberang Perai Tengah, Pulau Pinang         9     14000   
1                  Larut Matang, Perak         7     34000   
2                      Sandakan, Sabah      

In [ ]:
print(df.tail()) #prints last N rows. Default: 5

    id                               name        Unnamed: 2  \
55  56  Klinik 1 Malaysia Teluk Air Tawar   Teluk Air Tawar   
56  57      Klinik 1 Malaysia Teluk Intan       Teluk Intan   
57  58         Klinik 1 Malaysia Temerloh          Temerloh   
58  59       Klinik 1 Malaysia Wakaf Baru        Wakaf Baru   
59  60          Klinik 1Malaysia Kerinchi          Kerinchi   

                                              address address2  state_id  \
55  No.6, Lorong Teluk Air Tawar 14, Taman Air Taw...      NaN         9   
56  No.1 Taman Medan Maharaja, Jalan Kampung Banja...      NaN         7   
57  N0.12 Tingkat Bawah, Jalan Pak Sako 4, Bandar ...      NaN         6   
58  Lot PT30712, Wakaf Baru, Mukim Kuala Nerus, Ku...      NaN        13   
59  B-0-1, Blok B Kuarters DBKL, Jalan Pantai Perm...      NaN        14   

    postcode              city         tel         fax  website  email image  \
55     13050       Butterworth  04-3511080         NaN      NaN    NaN   NaN   
56  

In [ ]:
print(df.iloc[0:5,:])   # SLICING: accesses first 5 rows of data, and all columns

   id                                    name             Unnamed: 2  \
0   1             Klinik 1 Malaysia Alma Jaya              Alma Jaya   
1   2                Klinik 1 Malaysia Aulong                 Aulong   
2   3           Klinik 1 Malaysia Bandar Lela            Bandar Lela   
3   4    Klinik 1 Malaysia Bandar Puteri Jaya     Bandar Puteri Jaya   
4   5  Klinik 1 Malaysia Bandar seri Iskandar   Bandar seri Iskandar   

                                             address  \
0  No. 38, Tingkat Bawah , Lorong Alma Jaya II, T...   
1  N0 51 &53, Jalan Medan Bersatu, Taman Medan Be...   
2  Lot 7A &7B, Tingkat Bawah, Blok B Mile 1, Jala...   
3  No.41, Tingkat Bawah, Jalan Puteri Jaya 1/1, B...   
4  N0.32 Blod D, Bangunan Rumah Kedai, Bandar Ser...   

                              address2  state_id  postcode  \
0  Seberang Perai Tengah, Pulau Pinang         9     14000   
1                  Larut Matang, Perak         7     34000   
2                      Sandakan, Sabah      

In [ ]:
print(df.iloc[0:5,1:3]) # SLICING: first 5 rows of data, and 2 selected columns

                                     name             Unnamed: 2
0             Klinik 1 Malaysia Alma Jaya              Alma Jaya
1                Klinik 1 Malaysia Aulong                 Aulong
2           Klinik 1 Malaysia Bandar Lela            Bandar Lela
3    Klinik 1 Malaysia Bandar Puteri Jaya     Bandar Puteri Jaya
4  Klinik 1 Malaysia Bandar seri Iskandar   Bandar seri Iskandar


Pandas library is huge. You can have a look here: https://pandas.pydata.org/pandas-docs/stable/reference/frame.html

Some attributes (properties) are quite useful to get information of the dataframe.

In [ ]:
df.columns

Index(['id', 'name', 'Unnamed: 2', 'address', 'address2', 'state_id',
       'postcode', 'city', 'tel', 'fax', 'website', 'email', 'image',
       'latitude', 'longitude', 'likes', 'rating', 'status'],
      dtype='object')

In [ ]:
df.values

array([[1, 'Klinik 1 Malaysia Alma Jaya', ' Alma Jaya', ..., 0, 0, 'NEW'],
       [2, 'Klinik 1 Malaysia Aulong', ' Aulong', ..., 0, 0, 'NEW'],
       [3, 'Klinik 1 Malaysia Bandar Lela', ' Bandar Lela', ..., 0, 0,
        'NEW'],
       ...,
       [58, 'Klinik 1 Malaysia Temerloh', ' Temerloh', ..., 0, 0, 'NEW'],
       [59, 'Klinik 1 Malaysia Wakaf Baru', ' Wakaf Baru', ..., 0, 0,
        'NEW'],
       [60, 'Klinik 1Malaysia Kerinchi', 'Kerinchi', ..., 0, 0, 'NEW']],
      dtype=object)

In [ ]:
df.dtypes

id              int64
name           object
Unnamed: 2     object
address        object
address2       object
state_id        int64
postcode        int64
city           object
tel            object
fax            object
website       float64
email         float64
image          object
latitude        int64
longitude       int64
likes           int64
rating          int64
status         object
dtype: object

`dtypes` property tells us the data types of each column. Notice that string data is always denoted as "object". That is because the string class is used  and hence it is an object instance type.

In [ ]:
df.shape

(60, 18)

Just like Numpy, `shape` gets us the dimensions of the data. Think of dataframes like a two-dimensional array, the first number is the number of rows, and the second number is the number of columns.

Now, what if we want to access a particular slice of the data, but we cannot remember indices (numbers are really difficult to remember and unintuitive since it might change when data changes). Slicing an entire column out of a dataframe is simple:

In [ ]:
sr = df['city']
print(sr)
type(sr)

0             Bukit Mertajam
1                    Taiping
2                Bandar Lela
3              Sungai Petani
4       Bandar Seri Iskandar
5                Johor Bahru
6           Bandar Sri Indah
7                     Melaka
8                   Seremban
9                 Alor Gajah
10               Johor Bahru
11    Seberang Perai Selatan
12                      Jeli
13                      Ipoh
14                   Kemaman
15           Bukit Beruntung
16                    Melaka
17                    Marang
18             Hulu Selangor
19                 Penampang
20            Kuala Selangor
21              Kuala Lumpur
22                   Kuantan
23                Kota Bharu
24      Bandar Seri Iskandar
25              Kuala Lumpur
26                      Sibu
27                    Bachok
28                Georgetown
29                    Kangar
30                   Kuantan
31                Kota Bharu
32                     Kulim
33               Kelana Jaya
34            

pandas.core.series.Series

**Note**: Observe closely, that this sliced out column is actually...a Series! We can consider the column name as the key or index, to access the Series. So you can think anatomically, that a Dataframe (table) consists of many Series (columns). Here's a nice labelled diagram showing this concept:

![](https://geo-python.github.io/site/_images/pandas-structures-annotated.png)

In [ ]:
len(df)

60

Let's create a new DataFrame, with this Series `sr` in it... (very easy)

In [ ]:
fr = pd.DataFrame(sr)
fr

city
0           Bukit Mertajam
1                  Taiping
2              Bandar Lela
3            Sungai Petani
4     Bandar Seri Iskandar
5              Johor Bahru
6         Bandar Sri Indah
7                   Melaka
8                 Seremban
9               Alor Gajah
10             Johor Bahru
11  Seberang Perai Selatan
12                    Jeli
13                    Ipoh
14                 Kemaman
15         Bukit Beruntung
16                  Melaka
17                  Marang
18           Hulu Selangor
19               Penampang
20          Kuala Selangor
21            Kuala Lumpur
22                 Kuantan
23              Kota Bharu
24    Bandar Seri Iskandar
25            Kuala Lumpur
26                    Sibu
27                  Bachok
28              Georgetown
29                  Kangar
30                 Kuantan
31              Kota Bharu
32                   Kulim
33             Kelana Jaya
34                 Kuching
35               Pasir Mas
36            Kuala Lumpur
37           Petaling Jaya
38                Seremban
39              Alor Gajah
40             Johor Bahru
41                 Kuantan
42           Kota Kinabalu
43             Bayan Lepas
44                 Bintulu
45               Batu Cave
46                 Kuantan
47                   Kulai
48             Johor Bahru
49            Kuala Lumpur
50                    Muar
51                Seremban
52                   Nilai
53                  Kluang
54                    Miri
55             Butterworth
56             Teluk Intan
57                Temerloh
58        Kuala Terengganu
59            Kuala Lumpur

Let's generate more Series data and add them to the DataFrame...

In [ ]:
x = [np.random.randint(500, 1500) for p in range(0, len(fr))]
fr['patients'] = pd.Series(x)
fr['ratings'] = pd.Series(np.random.randn(len(fr)))

In [ ]:
fr

city  patients   ratings
0           Bukit Mertajam      1067  2.004763
1                  Taiping      1029  2.326612
2              Bandar Lela       954  0.587282
3            Sungai Petani       573  0.616794
4     Bandar Seri Iskandar      1325 -0.895282
5              Johor Bahru      1284  0.879843
6         Bandar Sri Indah       886 -0.337396
7                   Melaka       904  2.054708
8                 Seremban      1100 -0.246904
9               Alor Gajah      1373  1.321662
10             Johor Bahru       505 -1.048235
11  Seberang Perai Selatan      1146 -1.085751
12                    Jeli      1164  1.027894
13                    Ipoh      1416 -2.340618
14                 Kemaman      1358  1.310627
15         Bukit Beruntung      1426  1.317391
16                  Melaka      1219  0.594170
17                  Marang      1298 -0.188095
18           Hulu Selangor       588  1.091119
19               Penampang      1422 -1.607800
20          Kuala Selangor       641 -0.231026
21            Kuala Lumpur       856 -0.807448
22                 Kuantan       926 -0.801052
23              Kota Bharu      1094 -1.373252
24    Bandar Seri Iskandar       602  1.179252
25            Kuala Lumpur       526  1.993890
26                    Sibu      1102 -1.499909
27                  Bachok       684  0.510065
28              Georgetown       659 -0.318545
29                  Kangar      1163  1.894370
30                 Kuantan       768  0.186006
31              Kota Bharu      1192  0.256425
32                   Kulim       955 -0.616731
33             Kelana Jaya      1037  0.629555
34                 Kuching      1144  0.107998
35               Pasir Mas       975 -0.183452
36            Kuala Lumpur       735  1.732091
37           Petaling Jaya      1071  1.301927
38                Seremban      1212  1.745311
39              Alor Gajah       630 -1.126016
40             Johor Bahru      1252 -1.088122
41                 Kuantan      1298  0.268450
42           Kota Kinabalu      1405 -0.082987
43             Bayan Lepas      1028  0.310553
44                 Bintulu      1361 -0.213791
45               Batu Cave       873 -1.604328
46                 Kuantan      1133  0.105855
47                   Kulai       523  0.080797
48             Johor Bahru       654  0.589941
49            Kuala Lumpur      1359  0.705264
50                    Muar       775  0.746985
51                Seremban      1130  0.420012
52                   Nilai      1100  0.915136
53                  Kluang       720  1.345955
54                    Miri       722 -1.596610
55             Butterworth       754  0.243333
56             Teluk Intan      1116 -1.172965
57                Temerloh      1162 -0.564668
58        Kuala Terengganu       845  2.798511
59            Kuala Lumpur       682 -2.130596

We can remove rows and columns from a Dataframe using the `drop` function. To remove rows, just specify which rows (in a list) that you want it dropped.

In [ ]:
fr2 = fr.drop([50, 51])
fr2

#fr.drop([50, 51], inplace=True)    # to make it permanent in fr

city  patients   ratings
0           Bukit Mertajam      1067  2.004763
1                  Taiping      1029  2.326612
2              Bandar Lela       954  0.587282
3            Sungai Petani       573  0.616794
4     Bandar Seri Iskandar      1325 -0.895282
5              Johor Bahru      1284  0.879843
6         Bandar Sri Indah       886 -0.337396
7                   Melaka       904  2.054708
8                 Seremban      1100 -0.246904
9               Alor Gajah      1373  1.321662
10             Johor Bahru       505 -1.048235
11  Seberang Perai Selatan      1146 -1.085751
12                    Jeli      1164  1.027894
13                    Ipoh      1416 -2.340618
14                 Kemaman      1358  1.310627
15         Bukit Beruntung      1426  1.317391
16                  Melaka      1219  0.594170
17                  Marang      1298 -0.188095
18           Hulu Selangor       588  1.091119
19               Penampang      1422 -1.607800
20          Kuala Selangor       641 -0.231026
21            Kuala Lumpur       856 -0.807448
22                 Kuantan       926 -0.801052
23              Kota Bharu      1094 -1.373252
24    Bandar Seri Iskandar       602  1.179252
25            Kuala Lumpur       526  1.993890
26                    Sibu      1102 -1.499909
27                  Bachok       684  0.510065
28              Georgetown       659 -0.318545
29                  Kangar      1163  1.894370
30                 Kuantan       768  0.186006
31              Kota Bharu      1192  0.256425
32                   Kulim       955 -0.616731
33             Kelana Jaya      1037  0.629555
34                 Kuching      1144  0.107998
35               Pasir Mas       975 -0.183452
36            Kuala Lumpur       735  1.732091
37           Petaling Jaya      1071  1.301927
38                Seremban      1212  1.745311
39              Alor Gajah       630 -1.126016
40             Johor Bahru      1252 -1.088122
41                 Kuantan      1298  0.268450
42           Kota Kinabalu      1405 -0.082987
43             Bayan Lepas      1028  0.310553
44                 Bintulu      1361 -0.213791
45               Batu Cave       873 -1.604328
46                 Kuantan      1133  0.105855
47                   Kulai       523  0.080797
48             Johor Bahru       654  0.589941
49            Kuala Lumpur      1359  0.705264
52                   Nilai      1100  0.915136
53                  Kluang       720  1.345955
54                    Miri       722 -1.596610
55             Butterworth       754  0.243333
56             Teluk Intan      1116 -1.172965
57                Temerloh      1162 -0.564668
58        Kuala Terengganu       845  2.798511
59            Kuala Lumpur       682 -2.130596

Rows with index 50 and 51 have now been removed. Now, data removal can be a very serious thing and if you happened to make a mistake, it might be costly. Pandas operate in a safe way by not allowing changes to be made directly to the original dataframe that is being accessed. Notice that the rows were only dropped in the new dataframe `fr2`. The original dataframe `fr` remains the same.

In [ ]:
fr

city  patients   ratings
0           Bukit Mertajam      1067  2.004763
1                  Taiping      1029  2.326612
2              Bandar Lela       954  0.587282
3            Sungai Petani       573  0.616794
4     Bandar Seri Iskandar      1325 -0.895282
5              Johor Bahru      1284  0.879843
6         Bandar Sri Indah       886 -0.337396
7                   Melaka       904  2.054708
8                 Seremban      1100 -0.246904
9               Alor Gajah      1373  1.321662
10             Johor Bahru       505 -1.048235
11  Seberang Perai Selatan      1146 -1.085751
12                    Jeli      1164  1.027894
13                    Ipoh      1416 -2.340618
14                 Kemaman      1358  1.310627
15         Bukit Beruntung      1426  1.317391
16                  Melaka      1219  0.594170
17                  Marang      1298 -0.188095
18           Hulu Selangor       588  1.091119
19               Penampang      1422 -1.607800
20          Kuala Selangor       641 -0.231026
21            Kuala Lumpur       856 -0.807448
22                 Kuantan       926 -0.801052
23              Kota Bharu      1094 -1.373252
24    Bandar Seri Iskandar       602  1.179252
25            Kuala Lumpur       526  1.993890
26                    Sibu      1102 -1.499909
27                  Bachok       684  0.510065
28              Georgetown       659 -0.318545
29                  Kangar      1163  1.894370
30                 Kuantan       768  0.186006
31              Kota Bharu      1192  0.256425
32                   Kulim       955 -0.616731
33             Kelana Jaya      1037  0.629555
34                 Kuching      1144  0.107998
35               Pasir Mas       975 -0.183452
36            Kuala Lumpur       735  1.732091
37           Petaling Jaya      1071  1.301927
38                Seremban      1212  1.745311
39              Alor Gajah       630 -1.126016
40             Johor Bahru      1252 -1.088122
41                 Kuantan      1298  0.268450
42           Kota Kinabalu      1405 -0.082987
43             Bayan Lepas      1028  0.310553
44                 Bintulu      1361 -0.213791
45               Batu Cave       873 -1.604328
46                 Kuantan      1133  0.105855
47                   Kulai       523  0.080797
48             Johor Bahru       654  0.589941
49            Kuala Lumpur      1359  0.705264
50                    Muar       775  0.746985
51                Seremban      1130  0.420012
52                   Nilai      1100  0.915136
53                  Kluang       720  1.345955
54                    Miri       722 -1.596610
55             Butterworth       754  0.243333
56             Teluk Intan      1116 -1.172965
57                Temerloh      1162 -0.564668
58        Kuala Terengganu       845  2.798511
59            Kuala Lumpur       682 -2.130596

If you ever need to make permanent changes (overwriting the original data), you can use the parameter `inplace=True` to perform this [drop](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html) operation "in place", in the original dataframe.

**Q2**: Write the code (one line only!) to drop the "patients" column from DataFrame `fr2`. Ensure that the modification is done on the original dataframe.

In [ ]:
# fill in here
fr2.drop(columns='patients', inplace=True)


In [ ]:
fr2

city   ratings
0           Bukit Mertajam  2.004763
1                  Taiping  2.326612
2              Bandar Lela  0.587282
3            Sungai Petani  0.616794
4     Bandar Seri Iskandar -0.895282
5              Johor Bahru  0.879843
6         Bandar Sri Indah -0.337396
7                   Melaka  2.054708
8                 Seremban -0.246904
9               Alor Gajah  1.321662
10             Johor Bahru -1.048235
11  Seberang Perai Selatan -1.085751
12                    Jeli  1.027894
13                    Ipoh -2.340618
14                 Kemaman  1.310627
15         Bukit Beruntung  1.317391
16                  Melaka  0.594170
17                  Marang -0.188095
18           Hulu Selangor  1.091119
19               Penampang -1.607800
20          Kuala Selangor -0.231026
21            Kuala Lumpur -0.807448
22                 Kuantan -0.801052
23              Kota Bharu -1.373252
24    Bandar Seri Iskandar  1.179252
25            Kuala Lumpur  1.993890
26                    Sibu -1.499909
27                  Bachok  0.510065
28              Georgetown -0.318545
29                  Kangar  1.894370
30                 Kuantan  0.186006
31              Kota Bharu  0.256425
32                   Kulim -0.616731
33             Kelana Jaya  0.629555
34                 Kuching  0.107998
35               Pasir Mas -0.183452
36            Kuala Lumpur  1.732091
37           Petaling Jaya  1.301927
38                Seremban  1.745311
39              Alor Gajah -1.126016
40             Johor Bahru -1.088122
41                 Kuantan  0.268450
42           Kota Kinabalu -0.082987
43             Bayan Lepas  0.310553
44                 Bintulu -0.213791
45               Batu Cave -1.604328
46                 Kuantan  0.105855
47                   Kulai  0.080797
48             Johor Bahru  0.589941
49            Kuala Lumpur  0.705264
52                   Nilai  0.915136
53                  Kluang  1.345955
54                    Miri -1.596610
55             Butterworth  0.243333
56             Teluk Intan -1.172965
57                Temerloh -0.564668
58        Kuala Terengganu  2.798511
59            Kuala Lumpur -2.130596

We can also explore the data (getting some summary of statistics) by using the `describe` method:

In [ ]:
print(df.describe())

              id   state_id      postcode  website  email  latitude  \
count  60.000000  60.000000     60.000000      0.0    0.0      60.0   
mean   30.500000   7.350000  50157.850000      NaN    NaN       0.0   
std    17.464249   4.165333  29760.682202      NaN    NaN       0.0   
min     1.000000   1.000000   1000.000000      NaN    NaN       0.0   
25%    15.750000   4.000000  23350.000000      NaN    NaN       0.0   
50%    30.500000   7.000000  48000.000000      NaN    NaN       0.0   
75%    45.250000  11.000000  78757.500000      NaN    NaN       0.0   
max    60.000000  14.000000  97000.000000      NaN    NaN       0.0   

       longitude  likes  rating  
count       60.0   60.0    60.0  
mean         0.0    0.0     0.0  
std          0.0    0.0     0.0  
min          0.0    0.0     0.0  
25%          0.0    0.0     0.0  
50%          0.0    0.0     0.0  
75%          0.0    0.0     0.0  
max          0.0    0.0     0.0  


Becareful with using `describe()` if your data has not been cleaned yet! They can often give you incorrect results.

That's all for now. We will do more handling and manipulation of data in the next lab.

## Additional Exercises:

**AE1**: Multiply A with B, and then multiply A with C. Observe the outcome of two multiplication of Numpy arrays.

In [ ]:
import numpy as np

A = np.array([[1,3,5],[2,4,6]])
B = np.array([9, 8, 7])
C = np.array([[0,1],[1,0]])
print(A.shape)
print(B.shape)
print(C.shape)
print()

A_B = A*B
print(A_B)


(2, 3)
(3,)
(2, 2)

[[ 9 24 35]
 [18 32 42]]


The result of A multiply with C cannot be answer. It is because od the operands could not be broadcast together with shapes (2,3)(2,2)

**AE2**: Using the "clinic1M.csv" data file, count the number of clinics in each state.

In [ ]:
import pandas as pd

df

In [ ]:
import pandas as pd
places = pd.DataFrame(df['address2'])
places[['district','state']] = places['address2'].str.split(',',expand=True)
places['state'].replace(np.nan,'N/A',inplace=True)
states = places['state'].unique()
states_total = [len(places[x == places['state']]) for x in states]

state_clinics = pd.DataFrame(states,columns=['states'])
state_clinics['total'] = pd.Series(states_total)
print(state_clinics['total'].sum())
state_clinics

60


states  total
0       Pulau Pinang      5
1              Perak      4
2              Sabah      4
3              Kedah      2
4              Johor      6
5             Melaka      3
6           Kelantan      4
7         Terengganu      3
8           Selangor      6
9       Kuala Lumpur      5
10           Sarawak      4
11            Perlis      1
12            Pahang      3
13   Negeri Sembilan      3
14               N/A      7